In [1]:
pip install xgboost lightgbm catboost pandas scikit-learn

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Collecting catboost
  Downloading catboost-1.2.10-cp313-cp313-win_amd64.whl.metadata (1.5 kB)
Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: scikit-learn in c:\users\user\anaconda3\lib\site-packages (1.6.1)
Requirement already satisfied: numpy in c:\users\user\anaconda3\lib\site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in c:\users\user\anaconda3\lib\site-packages (from xgboost) (1.15.3)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\users\user\anaconda3\lib\site-packages (from catboost) (3.10.0)
Requirement already satisfied: plotly in c:\users\user\anaconda3\lib\site-packages (from catboost) (5.24.1)
Requirement already satisfied: six in c:\users\user\anaconda3\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->catboost) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->catboost) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->catboost) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->catboost) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->catboost) (3.2.0)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\user\anaconda3\lib\site-packages (from plotly->catboost) (9.0.0)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.5/101.7 MB 5.9 MB/s eta 0:00:18
   - -------------------------------------- 3.9/101.7 MB 13.6 MB/s eta 0:00:08
   -- ------------------------------------- 6.0/101.7 MB 12.8 MB/s eta 0:00:08
   --- ------------------------------------ 7.9/101.7 MB 11.2 MB/s eta 0:00:09
   --- ------------------------------------ 10.0/101.7 MB 10.6 MB/s eta 0:00:09
   ----- ---------------------------------- 12.8/101.7 MB 11.2 MB/s eta 0:00:08
   ------ --------------------------------- 15.7/101.7 MB 11.7 MB/s eta 0:00:08
   ------- -------------------------------- 18.1/101.7 MB 11.7 MB/s eta 0:00:08
   -------- ------------------------------- 20.7/101.7 MB 11.7 MB/s eta 0:00:07
   --------- ------------------------------ 23.6/101.7 MB 11.9 MB/s eta 0:00:07
   ---------- ----------------------------- 27.0/101.7 MB 12.3 MB/s eta 0:00:07
   ----------- ---------------------------- 30.1/101.7 MB 12.6 MB/s eta 0:00:06
   ------------ --------------------------- 32.5/101.7 MB 12.5 MB/s eta 0:00:06
   -------------- ------------------------- 36.2/101.7 MB 12.8 MB/s eta 0:00:06
   --------------- ------------------------ 39.6/101.7 MB 13.1 MB/s eta 0:00:05
   ---------------- ----------------------- 43.0/101.7 MB 13.3 MB/s eta 0:00:05
   ------------------ --------------------- 46.4/101.7 MB 13.5 MB/s eta 0:00:05
   ------------------- -------------------- 49.8/101.7 MB 13.6 MB/s eta 0:00:04
   -------------------- ------------------- 53.2/101.7 MB 13.7 MB/s eta 0:00:04
   ---------------------- ----------------- 56.1/101.7 MB 13.8 MB/s eta 0:00:04
   ----------------------- ---------------- 59.5/101.7 MB 13.9 MB/s eta 0:00:04
   ------------------------ --------------- 62.1/101.7 MB 13.8 MB/s eta 0:00:03
   ------------------------- -------------- 64.7/101.7 MB 13.7 MB/s eta 0:00:03
   -------------------------- ------------- 66.8/101.7 MB 13.5 MB/s eta 0:00:03
   --------------------------- ------------ 70.0/101.7 MB 13.6 MB/s eta 0:00:03
   ---------------------------- ----------- 73.4/101.7 MB 13.7 MB/s eta 0:00:03
   ----------------------------- ---------- 75.8/101.7 MB 13.6 MB/s eta 0:00:02
   ------------------------------- -------- 78.9/101.7 MB 13.6 MB/s eta 0:00:02
   -------------------------------- ------- 82.1/101.7 MB 13.7 MB/s eta 0:00:02
   --------------------------------- ------ 85.5/101.7 MB 13.8 MB/s eta 0:00:02
   ----------------------------------- ---- 89.1/101.7 MB 13.9 MB/s eta 0:00:01
   ------------------------------------ --- 92.3/101.7 MB 13.9 MB/s eta 0:00:01
   ------------------------------------- -- 95.7/101.7 MB 14.0 MB/s eta 0:00:01
   -------------------------------------- - 99.1/101.7 MB 14.0 MB/s eta 0:00:01
   --------------------------------------  101.4/101.7 MB 14.0 MB/s eta 0:00:01
   --------------------------------------- 101.7/101.7 MB 13.8 MB/s eta 0:00:00
Downloading lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 8.2 MB/s eta 0:00:00
Downloading catboost-1.2.10-cp313-cp313-win_amd64.whl (100.2 MB)
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
    --------------------------------------- 1.8/100.2 MB 9.0 MB/s eta 0:00:11
   - -------------------------------------- 4.5/100.2 MB 10.7 MB/s eta 0:00:09
   -- ------------------------------------- 7.3/100.2 MB 11.9 MB/s eta 0:00:08
   --- ------------------------------------ 10.0/100.2 MB 12.1 MB/s eta 0:00:08
   ----- ---------------------------------- 12.6/100.2 MB 12.0 MB/s eta 0:00:08
   ------ --------------------------------- 15.7/100.2 MB 12.5 MB/s eta 0:00:07
   ------- -------------------------------- 18.6/100.2 MB 12.8 MB/s eta 0:00:07
   -------- ------------------------------- 22.0/100.2 MB 13.2 MB/s eta 0:00:06
   ---------- ----------------------------- 25.4/100.2 MB 13.4 MB/s eta 0:00:06
   ----------- ---------------------------- 28.8/100.2 MB 13.7 MB/s eta 0:00:06
   ------------ --------------------------- 32.0/100.2 MB 13.7 MB/s eta 0:00:05
   ------------- -------------------------- 34.9/100.2 MB 13.8 MB/s eta 0:00:05
   --------------- ------------------------ 38.3/100.2 MB 13.9 MB/s eta 0:00:05
   ---------------- ----------------------- 40.4/100.2 MB 13.7 MB/s eta 0:00:05
   ---------------- ----------------------- 42.5/100.2 MB 13.4 MB/s eta 0:00:05
   ----------------- ---------------------- 44.8/100.2 MB 13.3 MB/s eta 0:00:05
   ------------------- -------------------- 48.2/100.2 MB 13.4 MB/s eta 0:00:04
   -------------------- ------------------- 51.1/100.2 MB 13.4 MB/s eta 0:00:04
   --------------------- ------------------ 53.5/100.2 MB 13.3 MB/s eta 0:00:04
   ---------------------- ----------------- 56.4/100.2 MB 13.3 MB/s eta 0:00:04
   ----------------------- ---------------- 59.2/100.2 MB 13.3 MB/s eta 0:00:04
   ------------------------ --------------- 62.1/100.2 MB 13.3 MB/s eta 0:00:03
   ------------------------- -------------- 64.7/100.2 MB 13.3 MB/s eta 0:00:03
   -------------------------- ------------- 67.4/100.2 MB 13.2 MB/s eta 0:00:03
   ---------------------------- ----------- 70.3/100.2 MB 13.2 MB/s eta 0:00:03
   ----------------------------- ---------- 72.9/100.2 MB 13.2 MB/s eta 0:00:03
   ------------------------------ --------- 75.8/100.2 MB 13.2 MB/s eta 0:00:02
   ------------------------------- -------- 78.9/100.2 MB 13.3 MB/s eta 0:00:02
   -------------------------------- ------- 82.1/100.2 MB 13.3 MB/s eta 0:00:02
   --------------------------------- ------ 84.9/100.2 MB 13.3 MB/s eta 0:00:02
   ----------------------------------- ---- 88.1/100.2 MB 13.4 MB/s eta 0:00:01
   ------------------------------------ --- 91.0/100.2 MB 13.4 MB/s eta 0:00:01
   ------------------------------------- -- 93.3/100.2 MB 13.3 MB/s eta 0:00:01
   -------------------------------------- - 95.4/100.2 MB 13.2 MB/s eta 0:00:01
   ---------------------------------------  98.3/100.2 MB 13.2 MB/s eta 0:00:01
   --------------------------------------  100.1/100.2 MB 13.2 MB/s eta 0:00:01
   --------------------------------------- 100.2/100.2 MB 13.0 MB/s eta 0:00:00
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Installing collected packages: graphviz, xgboost, lightgbm, catboost

   ---------- ----------------------------- 1/4 [xgboost]
   ---------- ----------------------------- 1/4 [xgboost]
   ---------- ----------------------------- 1/4 [xgboost]
   ---------- ----------------------------- 1/4 [xgboost]
   ---------- ----------------------------- 1/4 [xgboost]
   ---------- ----------------------------- 1/4 [xgboost]
   ---------- ----------------------------- 1/4 [xgboost]
   -------------------- ------------------- 2/4 [lightgbm]
   ------------------------------ --------- 3/4 [catboost]
   ------------------------------ --------- 3/4 [catboost]
   ------------------------------ --------- 3/4 [catboost]
   ------------------------------ --------- 3/4 [catboost]
   ------------------------------ --------- 3/4 [catboost]
   ------------------------------ --------- 3/4 [catboost]
   ------------------------------ --------- 3/4 [catboost]
   ------------------------------ --------- 3/4 [catboost]
   ---------------------------------------- 4/4 [catboost]

Successfully installed catboost-1.2.10 graphviz-0.21 lightgbm-4.6.0 xgboost-3.2.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import seaborn as sns

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.metrics import accuracy_score

In [4]:
df = pd.read_csv('C:/Users/User/FOR ML learnin stepik/TITANIK LEARN/train.csv')

In [5]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [15]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [7]:
df = df.drop('Cabin', axis=1)
## Удалить колонку 'Age' (создаёт новый DataFrame, если не указать inplace=True)
##df = df.drop('Age', axis=1)

# Или более явно с параметром columns
##df = df.drop(columns=['Age'])

# Удалить несколько колонок сразу
##df = df.drop(columns=['Age', 'Cabin', 'Ticket'])

# Удалить, изменяя исходный DataFrame (inplace=True)
##df.drop('Age', axis=1, inplace=True)

In [8]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [9]:
df = df.dropna(subset = ['Embarked'])

In [10]:
maen_age = df['Age'].mean()
df['Age'].fillna(maen_age, inplace = True)

C:\Users\User\AppData\Local\Temp\ipykernel_29488\1274005726.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(maen_age, inplace = True)
C:\Users\User\AppData\Local\Temp\ipykernel_29488\1274005726.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'].fillna(maen_age, inplace = True)

In [11]:
df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']]

     Pclass     Sex        Age  SibSp  Parch     Fare Embarked
0         3    male  22.000000      1      0   7.2500        S
1         1  female  38.000000      1      0  71.2833        C
2         3  female  26.000000      0      0   7.9250        S
3         1  female  35.000000      1      0  53.1000        S
4         3    male  35.000000      0      0   8.0500        S
..      ...     ...        ...    ...    ...      ...      ...
886       2    male  27.000000      0      0  13.0000        S
887       1  female  19.000000      0      0  30.0000        S
888       3  female  29.642093      1      2  23.4500        S
889       1    male  26.000000      0      0  30.0000        C
890       3    male  32.000000      0      0   7.7500        Q

[889 rows x 7 columns]

In [12]:
X = df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']]

In [13]:
y = df['Survived']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
#LightGBM умеет сам обрабатывать категории, но нужно указать, какие колонки категориальные.
import lightgbm as lgb

In [30]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    889 non-null    int64
 1   Sex       889 non-null    object
 2   Age       889 non-null    float64
 3   SibSp     889 non-null    int64
 4   Parch     889 non-null    int64
 5   Fare      889 non-null    float64
 6   Embarked  889 non-null    object
dtypes: float64(2), int64(3), object(2)
memory usage: 55.6+ KB

In [31]:
X[['Sex','Embarked']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Sex       889 non-null    object
 1   Embarked  889 non-null    object
dtypes: object(2)
memory usage: 20.8+ KB

In [33]:
# Категориальные признаки: sex и embarked (обратите внимание, тип данных должен быть 'category')
X_train_lgb = X_train.copy()
X_test_lgb = X_test.copy()

In [34]:
X_train_lgb['Sex'] = X_train_lgb['Sex'].astype('category')
X_test_lgb['Sex'] = X_test_lgb['Sex'].astype('category')

In [36]:
X_train_lgb['Embarked'] = X_train_lgb['Embarked'].astype('category')
X_test_lgb['Embarked'] = X_test_lgb['Embarked'].astype ('category')

In [38]:
# Заполним пропуски в возрастах (LightGBM сам с пропусками справится, но лучше заполнить).Я ранее вроде сделал средним значением. Просто строки
X_train_lgb['Age'] = X_train_lgb['Age'].fillna(X_train_lgb['Age'].mean())
X_test_lgb['Age'] = X_test_lgb['Age'].fillna(X_train_lgb['Age'].mean())

In [41]:
# Создаём модель с указанием категориальных фич
model_lgb = lgb.LGBMClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
model_lgb.fit(X_train_lgb, y_train, categorical_feature=['Sex', 'Embarked'])

[LightGBM] [Info] Number of positive: 271, number of negative: 440
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000174 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 203
[LightGBM] [Info] Number of data points in the train set: 711, number of used features: 7
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.381153 -> initscore=-0.484656
[LightGBM] [Info] Start training from score -0.484656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMClassifier(max_depth=3, random_state=42)

In [42]:
y_pred_lgb = model_lgb.predict(X_test_lgb)
print("LightGBM Accuracy:", accuracy_score(y_test, y_pred_lgb))

LightGBM Accuracy: 0.8146067415730337